const PERMISSIONS = {
    DASHBOARD: "DASHBOARD",

    ROLE_VIEW: "VIEW_ROLE_LIST",
    ROLE_CREATE: "CREATE_ROLE",
    ROLE_EDIT: "EDIT_ROLE",

    USER_VIEW: "user-view",
    USER_CREATE: "user-create",
    USER_EDIT: "user-update",

    VIEW_EMPLOYEE_LIST: "VIEW_EMPLOYEE_LIST",
    VIEW_ROLE_LIST: "VIEW_ROLE_LIST",
    VIEW_ATTENDANCE_LIST: "VIEW_ATTENDANCE_LIST",
    CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
    EDIT_EMPLOYEE_DETAIL: "EDIT_EMPLOYEE_DETAIL",
    VIEW_EMPLOYEE_DETAIL: "VIEW_EMPLOYEE_DETAIL",

    VIEW_CONTRACT_LIST: "VIEW_CONTRACT_LIST",
    CREATE_CONTRACT: "CREATE_CONTRACT",
    VIEW_CONTRACT_DETAIL: "VIEW_CONTRACT_DETAIL",
    EDIT_CONTRACT: "EDIT_CONTRACT",


    VIEW_PERSONAL_INFO: "VIEW_PERSONAL_INFO",
    VIEW_WORK: "VIEW_WORK",
    VIEW_CONFIG: "VIEW_CONFIG",
    EDIT_CONFIG: "EDIT_CONFIG",

};

export default PERMISSIONS;
